blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_view
)
app_name = "blog"
urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('<slug>/delete', delete_blog_view, name="delete"),
]

                        

blog_site/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from personal.views import (
     home_screen,
)
from account.views import (
    registration_view,logout_view,login_view,account_view,must_authenticate_view
    )
urlpatterns = [
    path('',home_screen, name = "home"),
    path('admin/', admin.site.urls),
    path('account/',account_view,name="account"),
    path('blog/',include('blog.urls','blog')),
    path('logout/',logout_view, name="logout"),
    path('login/',login_view,name="login"),
    path('must_authenticate/',must_authenticate_view,name="must_authenticate"),
    path('register/',registration_view, name="register"),

    


# Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='register_confirm'),

    path('account/confirm/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/register_email.html'),
     name='register_email'), 
     
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

personal/urls.py
from django.contrib import admin
from django.urls import path
from views import *
path('',home_screen(),name="home")

personal/models.py
from django.db import models

# # Create your models here.
# PRIORITY = [
#   ("L","Low"),
#   ("M","Medium"),
#   ("H","High"),
# ]
# # COLORS = [("R","Red"),
# #   ("Y","Yellow"),
# #   ("G","Green"),
# #   ("B","Blue"),
# #   ]
# class Question(models.Model):
#     title = models.CharField(max_length=50)
#     question = models.TextField(max_length=400)
#     priority = models.CharField(max_length=1,choices=PRIORITY)
#     #colors = models.CharField(max_length=1,choices=COLORS)
    
#     def __str__(self):
#         return self.title

#     class meta:
#       verbose_name = "The Questions"
#       verbose_name_plural = "People Questions"
    
    

personal/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from blog.models import Blogpost
from blog.views import get_blog_queryset


# Create your views here:
blog_post_per_page = 5
def home_screen(request):
    context = {}
    query = ""
    if request.GET:
        query = request.GET.get('q','')
        context['query'] = str(query)
    blog_posts = sorted(get_blog_queryset(query),key=attrgetter('date_update'), reverse=True)
    

    #Pagination
    page = request.GET.get('page',1)
    blog_posts_paginator = Paginator(blog_posts, blog_post_per_page)    

    try:
        blog_posts = blog_posts_paginator.page(page) 
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator(blog_post_per_page)
    except EmptyPage:
        blog_posts = blog_posts_paginator(blog_post_paginator.num_pages)
    
    context['blog_posts'] = blog_posts

    return render(request, "personal/home.html",context)

personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'Blog.png' %}" width="100%" height="100%">
					<p class="lead">
						{% if request.user.is_authenticated %}
						   Cool ! 
						   Now you can create your own blog post and write and express what you want through words, by clicking
						   the 'Create post' button below.
						{% else %}
						   You can only create a post after you login.
						   A blog is a chance to share your knowledge and ideas. 
						   So, <a href="{% url 'login' %}">Login</a> or if you're new then you can <a href="{% url 'register' %}">Register</a> here 
						   and share with world what you want.
						{% endif %}
					</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		    {% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'Blog.png' %}" alt="Bitcoin Photo" width="100%" height="100%">
				<p class="lead">
					{% if request.user.is_authenticated %}
					   Cool ! 
					   Now you can create your own blog post and write and express what you want through words, by clicking
					   the 'Create post' button below.
				    {% else %}
				       You can only create a post after you login.
				       A blog is a chance to share your knowledge and ideas. 
					   So, <a href="{% url 'login' %}">Login</a> or if you're new then you can <a href="{% url 'register' %}">Register</a> here 
					   and share with world what you want.
				    {% endif %}
				</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->



	</div>
</div>

{% endblock content %}